# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Saml configure and login
    command: |
      (
        set -e
        eval $(gp env -e)
        CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
        wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz -O - | tar -xzv -C ~/.local/bin
        chmod u+x ~/.local/bin/saml2aws
        hash -r
        saml2aws --version
        saml2aws configure --idp-provider KeyCloak --mfa Auto \
        --url https://devfactory.devconnect-df.com/auth/realms/devfactory/protocol/saml/clients/aws --skip-prompt --profile default
        # Check if AD_USERNAME environment variable is set
        if [[ -n "$AD_USERNAME" ]]; then
          if [[ -n "$AD_PASSWORD" ]]; then
            # Login with provided username and password
            saml2aws login --username="$AD_USERNAME" --password="$AD_PASSWORD" --skip-prompt
          else
            # Login with provided username, prompting for password
            saml2aws login --username="$AD_USERNAME"
          fi
        else
          # Login without providing username and password (relying on SAML2AWS configuration)
          saml2aws login
        fi
      )  
  - name: Python Setup
    command: |
      pyenv install 3.9.12
      pyenv local 3.9.12
      export PYENV_VERSION=3.9.12
      gp sync-done python
  - name: SAM Setup
    command: |
      gp sync-await python
      pip install --upgrade aws-sam-cli
      gp sync-done sam
  - name: Setup Project
    init: |
      gp sync-await sam
      # pip install -r setup/requirements.txt
      # python setup/git_hooks.py
      # python setup/dev.py
      bash scripts/init.sh
  - name: Install Promptfoo
    init: |
      nvm install v18.16.0
      nvm use v18.16.0
      npm install -g npm
      npm install -g promptfoo