name: Deploy

on:
  push:
    branches: [ ci-cd ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

env:
  RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
  # where to put AWS creds, in github repo secrets

jobs:
  check:
    outputs:
      status: ${{ steps.check_env_file.outputs.files_exists }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check Enc Env file existence
        id: check_env_file
        uses: andstor/file-existence-action@v2
        with:
          files: "env/.env.${{ github.ref_name }}.enc"

  deploy:
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.status == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set up Python 3.9.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12

      # Decrypt Encrypted Env file
      - name: Load env
        run: |
          pip install -r setup/requirements.txt
          python setup/load_env.py "env/.env.${{ github.ref_name }}.enc"

      # Load .env file
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./

      - name: Set stage
        id: vars
        run: echo "::set-output name=stage::$(if [[ "${{ github.ref_type }}" == "tag" ]]; then echo 'prod'; else echo 'dev'; fi)"

      - name: Package, Check/Create S3 Bucket, and Deploy
        run: |
         bash scripts/deploy.sh --stage ${{ steps.vars.outputs.stage }} --update_secrets true
        